/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package u2a7_flight;

import java.util.ArrayList;

/**
 *
 * @author Atul
 * The purpose of this program is to create a GUI that can hold input from a user with the help of arrays. 
 * In this case it is a flight rewards /points tracking application where each rewards user can store their 
 * information and have it be added to the database listed it, or tallied. It also can check if the user
 * has qualified for bonus points and adds them if so
 */
class FlightPointsData {
    //Creates variables to store the inputted data
    String firstName,lastName, week1Points, week2Points, week3Points, week4Points;
    //Creating a class constructor so that everytime the class is called upon, it requires certain data to be inputted
    public FlightPointsData (String _firstName, String _lastName,String _week1Points, String _week2Points, String _week3Points, String _week4Points) {
        //Assigns the inputted data to variables
        firstName = _firstName;
        lastName = _lastName;
        week1Points = _week1Points;
        week2Points = _week2Points;
        week3Points = _week3Points;
        week4Points = _week4Points;
        
    }
}
public class FlightGUI extends javax.swing.JFrame {
    //Creates the ArrayList that the data will be stored in
    ArrayList<FlightPointsData> pointsInfo = new ArrayList<FlightPointsData>();
    /**
     * Creates new form FlightGUI
     */
    public FlightGUI() {
        super ("Super Airlines Point Manager");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        week1Label = new javax.swing.JLabel();
        week2Label = new javax.swing.JLabel();
        week3Label = new javax.swing.JLabel();
        week4Label = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        week1Input = new javax.swing.JTextField();
        week2Input = new javax.swing.JTextField();
        week3Input = new javax.swing.JTextField();
        week4Input = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        list = new javax.swing.JButton();
        totalPoints = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputDisplay = new javax.swing.JTextArea();
        bonusDisplay = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setText("Airline Points");

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/u2a7_flight/planeimage.jpg"))); // NOI18N

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/u2a7_flight/planeimage.jpg"))); // NOI18N

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        week1Label.setText("Week 1:");

        week2Label.setText("Week 2:");

        week3Label.setText("Week 3:");

        week4Label.setText("Week 4:");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        list.setText("List");
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        totalPoints.setText("Total Points");
        totalPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPointsActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        outputDisplay.setColumns(20);
        outputDisplay.setRows(5);
        jScrollPane1.setViewportView(outputDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(image1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(week1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(week2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(week3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(week4Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(week1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(week4Input, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(week3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(week2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(list)
                                            .addComponent(add))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(totalPoints)
                                            .addComponent(exit))
                                        .addGap(61, 61, 61))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(image2)
                            .addComponent(bonusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(firstNameLabel)
                                .addComponent(lastNameLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(week1Label)
                                .addComponent(week1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalPoints)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(week2Label)
                            .addComponent(week2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list)
                            .addComponent(exit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(week3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(week3Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(week4Label)
                                    .addComponent(week4Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bonusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(image2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Adds data to the ArrayList
 * @param evt 
 */
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        //Getting the input data and assigning it to variables
        String firstName = firstNameInput.getText();  
        String lastName = lastNameInput.getText();
        String week1Points = week1Input.getText();
        String week2Points = week2Input.getText();
        String week3Points = week3Input.getText();
        String week4Points = week4Input.getText();
       //Creates a new instance of the FlightPointsData class to sort the data
        FlightPointsData data = new FlightPointsData(firstName,lastName,week1Points,week2Points,week3Points,week4Points);
        //Then adds it to the arraylist
        pointsInfo.add(data);
    }//GEN-LAST:event_addActionPerformed
/**
 * Lists the data from the ArrayList
 * @param evt 
 */
    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        //Creates an empty string
        String temp= "";
        //Goes through the ArrayList and takes all the data inside of it and adds it to that string
        for (int i=0; i<pointsInfo.size(); i++) { 
            temp = temp + pointsInfo.get(i).firstName + " "
                    + pointsInfo.get(i).lastName + ": "
                    + pointsInfo.get(i).week1Points + " "
                    + pointsInfo.get(i).week2Points + " " 
                    + pointsInfo.get(i).week3Points + " " 
                    + pointsInfo.get(i).week4Points + "\n";
        }
        //Then displays it on the output text area
        outputDisplay.setText(temp);
    }//GEN-LAST:event_listActionPerformed
/**
 * Totals the amount of points the person has
 * @param evt 
 */
    private void totalPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPointsActionPerformed
       
        //Get the name of the person and create a temp string that will be outputted
        String firstName = firstNameInput.getText(); 
        String lastName = lastNameInput.getText(); 
        String temp = "";
                
        //Then create integers so the values can be totaled up.
        int week1Points = 0;
        int week2Points = 0;
        int week3Points = 0;
        int week4Points = 0;
        int totalPoints = 0;
        int amountOfBonuses = 0;
        int bonusTotal = 0;
        //Goes through the Arraylist and checks for that id number, if it is found it removes its data
        for (int i=0; i<pointsInfo.size(); i++) {
            if (pointsInfo.get(i).firstName.equals(firstName) && pointsInfo.get(i).lastName.equals(lastName)) {
               //Assign the values of the points to variables
               week1Points = Integer.parseInt(pointsInfo.get(i).week1Points);
               week2Points = Integer.parseInt(pointsInfo.get(i).week2Points);
               week3Points = Integer.parseInt(pointsInfo.get(i).week3Points);
               week4Points = Integer.parseInt(pointsInfo.get(i).week4Points);
               totalPoints = week1Points + week2Points + week3Points + week4Points;
               //Checks how many bonuses the person is valid for
               //Math.floor(); rounds downwards to the nearest integer, so for ex 1.5 wont become 2
               amountOfBonuses = (int) Math.floor(totalPoints/5000);
               bonusTotal = amountOfBonuses * 1000;
               //Displays in the bottom right if the person is eligible for any bonuses
               
               if (amountOfBonuses == 1) {
                   bonusDisplay.setText(firstName + " is eligible for " + amountOfBonuses + " bonus!");
               }
               else if (amountOfBonuses > 1) {
                   bonusDisplay.setText(firstName + " is eligible for " + amountOfBonuses + " bonuses!");
               }
               else {
                   bonusDisplay.setText(firstName + " is not eligible for any bonuses!");
               }
               
               //Then creates the string that will be outputted
               temp = firstName + "'s Total Points: " + totalPoints + " Bonus: " + bonusTotal;
               
            }
        }
        //And display it on the output textarea
        outputDisplay.setText(temp);
    }//GEN-LAST:event_totalPointsActionPerformed
/**
 * Exits the program
 * @param evt 
 */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField bonusDisplay;
    private javax.swing.JButton exit;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton list;
    private javax.swing.JTextArea outputDisplay;
    private javax.swing.JLabel title;
    private javax.swing.JButton totalPoints;
    private javax.swing.JTextField week1Input;
    private javax.swing.JLabel week1Label;
    private javax.swing.JTextField week2Input;
    private javax.swing.JLabel week2Label;
    private javax.swing.JTextField week3Input;
    private javax.swing.JLabel week3Label;
    private javax.swing.JTextField week4Input;
    private javax.swing.JLabel week4Label;
    // End of variables declaration//GEN-END:variables
}
