/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package u2a2_sumelement;
import java.util.*;

/**
 *
 * @author Atul
 * Date: 2022-03-22
 * Name: Sum Element
 * Purpose: The purpose of this assignment is to learn about how to use arrays in Java. Arrays are one
 * of the most common ways of storing data. This program takes user inputted numbers and stores them,
 * then allows them to sum all of the stored numbers, or only sum the even/odd numbers. All the numbers
 * can be displayed at any time for user ease as well.
 */
public class sumElementGUI extends javax.swing.JFrame {
    //Declaring variables that will be used throughout
    //The arraylist will be used to store the inputted numbers
    //And the other wrapper class integers are used to read what is being inputted and to calculate sum
    ArrayList<Integer> inputList = new ArrayList<>();
    static Integer inputNum;
    static Integer sumInt;
    
    /**
     * Creates new form sumElementGUI
     */
    public sumElementGUI() {
        super ("Integer Sum");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        IntegerInputLabel = new javax.swing.JLabel();
        Input = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        List = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        SumAll = new javax.swing.JButton();
        SumEven = new javax.swing.JButton();
        SumOdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputBox = new javax.swing.JTextArea();
        SumOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 0, 0));
        Title.setText("Integer Sums");

        IntegerInputLabel.setText("Enter an Integer:");

        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        List.setText("List");
        List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        SumAll.setText("Sum All");
        SumAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumAllActionPerformed(evt);
            }
        });

        SumEven.setText("Sum Even");
        SumEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumEvenActionPerformed(evt);
            }
        });

        SumOdd.setText("Sum Odd");
        SumOdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumOddActionPerformed(evt);
            }
        });

        OutputBox.setColumns(20);
        OutputBox.setRows(5);
        jScrollPane1.setViewportView(OutputBox);

        SumOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(IntegerInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(Remove))
                            .addComponent(Clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SumAll)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Add)
                                .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SumEven)
                            .addComponent(SumOdd)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SumOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntegerInputLabel)
                    .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add)
                    .addComponent(Remove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(List)
                    .addComponent(Clear))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Exit)
                        .addGap(18, 18, 18)
                        .addComponent(SumAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SumEven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SumOdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(SumOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        //These lines clear all the boxes and empty the arraylist
        inputList.clear();
        OutputBox.setText("");
        Input.setText("");
        SumOutput.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        //Exits the program
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void SumOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumOutputActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        //Takes the value of the inputted number, then adds it to the arraylist
        inputNum = Integer.parseInt(Input.getText());
        inputList.add(inputNum);
        Input.setText("");
    }//GEN-LAST:event_AddActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        //Takes the value of the inputted number, and removes it from the arraylist 
        //(does nothing if the value is not in the arraylist)
        inputNum = Integer.parseInt(Input.getText());
        inputList.remove(inputNum);
        Input.setText("");
        
    }//GEN-LAST:event_RemoveActionPerformed

    private void ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListActionPerformed
        //First clears the box so nothing overlaps
        OutputBox.setText("");
        for (Integer num: inputList) { // Takes everyvalue within the arraylist, then adds it to the outputbox
            OutputBox.append(num.toString() + "\n");
        }
    }//GEN-LAST:event_ListActionPerformed

    private void SumAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumAllActionPerformed
        //Clears the box then sets the current sum to 0
        OutputBox.setText("");
        sumInt = 0;
        //Checks all the values in the arraylist, the prints them and adds them up
        for (Integer num: inputList) {
            OutputBox.append(num.toString() + "\n");
            sumInt+=num;
        }
        //Then displays the sum of all values
        SumOutput.setText("The total of the entries is: " + sumInt.toString());
    }//GEN-LAST:event_SumAllActionPerformed

    private void SumEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumEvenActionPerformed
        //Clears the box then sets the current sum to 0
        OutputBox.setText("");
        sumInt = 0;
        //Checks all the values in the arraylist that are even the prints them and adds them up
        for (Integer num: inputList) {
            if (num % 2 == 0) { //This checks if the number divided by 2 is 0, which means it is even
                OutputBox.append(num.toString() + "\n");
                sumInt+=num;
            }
        }
        //Then displays the sum of all values
        SumOutput.setText("The total of the entries is: " + sumInt.toString());
    }//GEN-LAST:event_SumEvenActionPerformed

    private void SumOddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumOddActionPerformed
        //Clears the box then sets the current sum to 0
        OutputBox.setText("");
        sumInt = 0;
        //Checks all the values in the arraylist that are odd the prints them and adds them up
        for (Integer num: inputList) {
            if (num % 2 != 0) { //This checks if the number divided by 2 is NOT 0, which means it is odd
                OutputBox.append(num.toString() + "\n");
                sumInt+=num;
            }
        }
        //Then displays the sum of all values
        SumOutput.setText("The total of the entries is: " + sumInt.toString());
    }//GEN-LAST:event_SumOddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sumElementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sumElementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sumElementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sumElementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sumElementGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Input;
    private javax.swing.JLabel IntegerInputLabel;
    private javax.swing.JButton List;
    private javax.swing.JTextArea OutputBox;
    private javax.swing.JButton Remove;
    private javax.swing.JButton SumAll;
    private javax.swing.JButton SumEven;
    private javax.swing.JButton SumOdd;
    private javax.swing.JTextField SumOutput;
    private javax.swing.JLabel Title;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
