/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package change;

/**
 *
 * @author tv40148, Atul R
 */
public class ChangeGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChangeGUI
     */
    public ChangeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        EnterCurrency = new javax.swing.JLabel();
        InputFormat = new javax.swing.JLabel();
        txtEntry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AmountReDisplay = new javax.swing.JTextField();
        QuartersLabel = new javax.swing.JLabel();
        NickelsLabel = new javax.swing.JLabel();
        DimesLabel = new javax.swing.JLabel();
        PenniesLabel = new javax.swing.JLabel();
        LooniesLabel = new javax.swing.JLabel();
        txtToonies = new javax.swing.JTextField();
        txtLoonies = new javax.swing.JTextField();
        txtQuarters = new javax.swing.JTextField();
        txtDimes = new javax.swing.JTextField();
        txtNickels = new javax.swing.JTextField();
        txtPennies = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        TooniesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 0, 0));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Change Exchange");

        EnterCurrency.setText("Enter Currency:");

        InputFormat.setText("Amount (xxxx.xx)");

        txtEntry.setName("txtAmount"); // NOI18N
        txtEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntryActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount:");

        AmountReDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountReDisplayActionPerformed(evt);
            }
        });

        QuartersLabel.setText("Quarters");

        NickelsLabel.setText("Nickels");

        DimesLabel.setText("Dimes");

        PenniesLabel.setText("Pennies");

        LooniesLabel.setText("Loonies");

        txtToonies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTooniesActionPerformed(evt);
            }
        });

        txtDimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDimesActionPerformed(evt);
            }
        });

        btnCalc.setText("Calculate");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        TooniesLabel.setText("Toonies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EnterCurrency)
                                    .addComponent(btnCalc))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(txtEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(btnExit))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(InputFormat))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(QuartersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DimesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDimes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NickelsLabel)
                                    .addComponent(PenniesLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNickels, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPennies, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TooniesLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtToonies, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LooniesLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(AmountReDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Title)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterCurrency)
                    .addComponent(txtEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputFormat)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalc)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountReDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuartersLabel)
                    .addComponent(NickelsLabel)
                    .addComponent(txtQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNickels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LooniesLabel)
                    .addComponent(txtLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DimesLabel)
                    .addComponent(PenniesLabel)
                    .addComponent(txtDimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPennies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TooniesLabel)
                    .addComponent(txtToonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntryActionPerformed

    private void txtDimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDimesActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // Creating initial variables
        double amount;
        int intAmount;
        int toonies;
        int loonies;
        int quarters;
        int dimes;
        int nickels;
        int pennies;
        
        amount = Double.parseDouble(txtEntry.getText()); //get the text from the amount text box
        AmountReDisplay.setText(Double.toString(amount));
        amount = amount * 10 * 10; //convert the amount to cents so as to not work with decimals
        
        intAmount = (int)(amount); //convert to integers from double
        
        
        //calculate toonies (200 cents = 2 dollars)
        // We start from the highest value (toonies),
        // as we are trying to make the least amount of coins,
        // so finding going from biggest to smallest allows for that
        toonies = intAmount / 200; //calculate how many toonies are in the amount by dividing by 200
        intAmount = intAmount % 200; //the % calculates the modulus which is the remainder of division,
                                     //which gives us what is left over after diving by 25, 
                                     //so we can calculate the rest of the numbers
                                     
        //calculate loonies (100 cents = 1 dollar)
        loonies = intAmount / 100; //calculate how many toonies are in the amount by dividing by 100
        intAmount = intAmount % 100;
        
        //calculate quarters
        quarters = intAmount / 25; //calculate how many quarters are in the amount by dividing by 25
        intAmount = intAmount % 25; 
                                                                        
        //calculate dimes then leftover
        dimes = intAmount/10;
        intAmount = intAmount % 10;
        
        //calculate nickels then leftover
        nickels = intAmount / 5;
        intAmount = intAmount % 5;
        
        //whatever is left over is pennies
        pennies = intAmount;
        
        //Outputs/Displays the amount of coins to their respective boxes
        
        txtToonies.setText(Integer.toString(toonies));
        txtLoonies.setText(Integer.toString(loonies));
        txtQuarters.setText(Integer.toString(quarters));
        txtDimes.setText(Integer.toString(dimes));
        txtNickels.setText(Integer.toString(nickels));
        txtPennies.setText(Integer.toString(pennies));
               
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtTooniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTooniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTooniesActionPerformed

    private void AmountReDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountReDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountReDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountReDisplay;
    private javax.swing.JLabel DimesLabel;
    private javax.swing.JLabel EnterCurrency;
    private javax.swing.JLabel InputFormat;
    private javax.swing.JLabel LooniesLabel;
    private javax.swing.JLabel NickelsLabel;
    private javax.swing.JLabel PenniesLabel;
    private javax.swing.JLabel QuartersLabel;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TooniesLabel;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDimes;
    private javax.swing.JTextField txtEntry;
    private javax.swing.JTextField txtLoonies;
    private javax.swing.JTextField txtNickels;
    private javax.swing.JTextField txtPennies;
    private javax.swing.JTextField txtQuarters;
    private javax.swing.JTextField txtToonies;
    // End of variables declaration//GEN-END:variables
}
